// Fill in  your WiFi networks SSID and password

#define SECRET_SSID "1771247"
#define SECRET_PASS "8003tjdals!"

// Fill in the hostname of your AWS IoT broker
#define SECRET_BROKER "
a1x12vdqpqr7kl-ats.iot.ap-northeast-2.amazonaws.com"

// Fill in the boards public certificate
const char SECRET_CERTIFICATE[] = R"(
-----BEGIN CERTIFICATE-----
MIICiDCCAXCgAwIBAgIUEmV1w+StO96eLq/wfeIXfWIEEO4wDQYJKoZIhvcNAQEL
BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g
SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTIyMTIwMjA2Mjcx
NFoXDTQ5MTIzMTIzNTk1OVowGDEWMBQGA1UEAxMNTXlNS1JXSUZJMTAxMDBZMBMG
ByqGSM49AgEGCCqGSM49AwEHA0IABN6aQ4PfS/hbxu/ii1q2fgwB19Bur4eWm1LK
ZPVfuW+wg5le7lVSSMK0VSNflcGQ+yP91gKKwfvpi1Uf2mtQllmjYDBeMB8GA1Ud
IwQYMBaAFKfqguO8lEcL3GoWOlWMpUVw154eMB0GA1UdDgQWBBRGn8jlent1ST7x
70HrtnJyRRhxEjAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB/wQEAwIHgDANBgkqhkiG
9w0BAQsFAAOCAQEAAGJJAR4UopptIzREQtIBJxNHznV06+AlVq8LGS1YLigTruZo
TuR2slsx+p/7b6lAVYPBP/3VUXmYM6SfzSCHCs+1dvwALtNz8FqTzS7UvdrftF0V
ZcjX+MWsqu9W5KV6bCTBNcFBUAZ+38V78NA7vb5ofVkDLSCQli8NeGD6JBpTvBnb
lK4KwgzCsR38aHpNkRPAGOlFyAftoGm8Et4VUvpKEhgpAtqtTmL+xAAX3P6fmbFB
S3QXLKOHBFrrXqLE72D8BHn0yh7aJi3w/BTCnkDO108gaYDdHNX5qmBQeOL7jTDY
TU3Kb6NjvRIkdczpBV1aMaLUTGAoNhAbnpXMVQ==
-----END CERTIFICATE-----
)";
